/*
 *Generated by FuchsGUICodeGenerator
 *Ghoshehsoft@live.com
 *www.ghoshehsoft.wordpress.com
 *Time of generation: 2/9/2011 2:08:26 AM
*/

using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Content;

using FuchsGUI;

namespace GUI
{
    public sealed class ABS_DataForm  : Form
    {
        ContentManager contentManager;

        #region Fields

        public Button Hide;
        public Label label3;
        public Button Button_surface;
        public Label label2;
        public Label label1;
        public Label label20;
        public Label label23;
        public Label label17;
        public Label Mu;
        public Label label16;
        public Label label19;
        public Label label18;
        public Label label12;
        public TextBox Moment_Of_Inertia_T;
        public TextBox Mu_Dervied_T;
        public TextBox B_Pacejka_Formula_T;
        public TextBox Mu_low;
        public TextBox Mu_Peak;
        public TextBox ABS_Status_T;
        public TextBox Mu_T;
        public TextBox C_Pacejka_Formula_T;
        public TextBox A_Pacejka_Formula_T;
        public TextBox LongitudinalSlipRatio_T;
        public DomainLeftRight Surface_Type;

        #endregion

        public ABS_DataForm(Texture2D texture, SpriteFont font, Color foreColor, ContentManager contentManager)
            : base("ABS_GroupBox", "ABSData", new Rectangle(12, 12, 300, 750), texture, font, foreColor, null)
        {
            this.contentManager = contentManager;
            this.AddControls();
        }

        void AddControls()
        {
            Texture2D texButton = contentManager.Load<Texture2D>(@"GUI\texButton");
            Texture2D texTextBox = contentManager.Load<Texture2D>(@"GUI\texTextBox");
            Texture2D texDomainLeftRight = contentManager.Load<Texture2D>(@"GUI\texDomainLeftRight");
            Texture2D texDomainLeft = contentManager.Load<Texture2D>(@"GUI\texDomainLeft");
            Texture2D texDomainRight = contentManager.Load<Texture2D>(@"GUI\texDomainRight");


            Hide = new Button("Hide", @"Hide", new Rectangle(255, 368, 45, 26), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(Hide);

            label3 = new Label("label3", @"Surface Type", new Vector2(25, 69), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label3);

            Button_surface = new Button("Button_surface", @"Enable", new Rectangle(25, 19, 115, 31), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(Button_surface);

            label2 = new Label("label2", @"Mu_low", new Vector2(159, 110), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label2);

            label1 = new Label("label1", @"Mu_Peak", new Vector2(25, 110), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label1);

            label20 = new Label("label20", @"Moment Of Inertia", new Vector2(25, 315), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label20);

            label23 = new Label("label23", @"Mu Dervied", new Vector2(25, 341), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label23);

            label17 = new Label("label17", @"B Pacejka Formula", new Vector2(25, 231), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label17);

            Mu = new Label("Mu", @"Mu(S)", new Vector2(25, 286), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(Mu);

            label16 = new Label("label16", @"A Pacejka Formula", new Vector2(25, 202), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label16);

            label19 = new Label("label19", @"ABS System Status", new Vector2(25, 140), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label19);

            label18 = new Label("label18", @"C Pacejka Formula", new Vector2(25, 259), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label18);

            label12 = new Label("label12", @"Longitudinal Slip Ratio", new Vector2(25, 172), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label12);

            Moment_Of_Inertia_T = new TextBox("Moment_Of_Inertia_T", @"", 32767, "", new Rectangle(159, 315, 100, 21), texTextBox, font, new Color(0, 0, 0), null);
            Moment_Of_Inertia_T.ReadOnly = true;
            this.AddControl(Moment_Of_Inertia_T);

            Mu_Dervied_T = new TextBox("Mu_Dervied_T", @"", 32767, "", new Rectangle(159, 341, 100, 21), texTextBox, font, new Color(0, 0, 0), null);
            Mu_Dervied_T.ReadOnly = true;
            this.AddControl(Mu_Dervied_T);

            B_Pacejka_Formula_T = new TextBox("B_Pacejka_Formula_T", @"", 32767, "", new Rectangle(159, 228, 100, 21), texTextBox, font, new Color(0, 0, 0), null);
            B_Pacejka_Formula_T.ReadOnly = true;
            this.AddControl(B_Pacejka_Formula_T);

            Mu_low = new TextBox("Mu_low", @"", 8, "0123456789.", new Rectangle(207, 107, 52, 21), texTextBox, font, new Color(0, 0, 0), null);
            this.AddControl(Mu_low);

            Mu_Peak = new TextBox("Mu_Peak", @"", 8,"0123456789.", new Rectangle(78, 107, 62, 21), texTextBox, font, new Color(0, 0, 0), null);
            this.AddControl(Mu_Peak);

            ABS_Status_T = new TextBox("ABS_Status_T", @"", 32767, "", new Rectangle(159, 137, 100, 21), texTextBox, font, new Color(0, 0, 0), null);
            ABS_Status_T.ReadOnly = true;
            this.AddControl(ABS_Status_T);

            Mu_T = new TextBox("Mu_T", @"", 32767, "", new Rectangle(159, 286, 100, 21), texTextBox, font, new Color(0, 0, 0), null);
            Mu_T.ReadOnly = true;
            this.AddControl(Mu_T);

            C_Pacejka_Formula_T = new TextBox("C_Pacejka_Formula_T", @"", 32767, "", new Rectangle(159, 256, 100, 21), texTextBox, font, new Color(0, 0, 0), null);
            C_Pacejka_Formula_T.ReadOnly = true;
            this.AddControl(C_Pacejka_Formula_T);

            A_Pacejka_Formula_T = new TextBox("A_Pacejka_Formula_T", @"", 32767, "", new Rectangle(159, 199, 100, 21), texTextBox, font, new Color(0, 0, 0), null);
            A_Pacejka_Formula_T.ReadOnly = true;
            this.AddControl(A_Pacejka_Formula_T);

            LongitudinalSlipRatio_T = new TextBox("LongitudinalSlipRatio_T", @"", 32767, "", new Rectangle(159, 169, 100, 21), texTextBox, font, new Color(0, 0, 0), null);
            LongitudinalSlipRatio_T.ReadOnly = true;
            this.AddControl(LongitudinalSlipRatio_T);

            Surface_Type = new DomainLeftRight("Surface_Type", new Rectangle(120, 68, 155, 21), texDomainLeftRight, texDomainLeft, texDomainRight, font, new Color(0, 0, 0), null);
            Surface_Type.AddItem("Dry Asphalt");
            Surface_Type.AddItem("Wet Asphalt / little Water");
            Surface_Type.AddItem("Wet Asphalt / dense water");
            Surface_Type.AddItem("New snow");
            Surface_Type.AddItem("Compressed snow");
            Surface_Type.AddItem("Ice");
            Surface_Type.AddItem("Other");
            this.AddControl(Surface_Type);


        }
    }
}