/*
 *Generated by FuchsGUICodeGenerator
 *Ghoshehsoft@live.com
 *www.ghoshehsoft.wordpress.com
 *Time of generation: 2/9/2011 2:49:32 AM
*/

using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Content;

using FuchsGUI;

namespace GUI
{
    public sealed class ESPForm : Form
    {
        ContentManager contentManager;

        #region Fields

        public Button Hide;
        public Label l_f;
        public Label L_r;
        public Label label22;
        public Label label21;
        public Label label20;
        public Label label12;
        public Label label11;
        public Label label10;
        public Label label9;
        public Label label8;
        public Label label19;
        public Label label24;
        public Label label7;
        public Label label18;
        public Label label23;
        public Label label6;
        public Label label5;
        public Label label4;
        public Label label3;
        public Label label2;
        public Label label13;
        public Label label16;
        public Label label15;
        public Label label14;
        public Label label17;
        public Label label1;
        public TextBox L_fT;
        public TextBox ESPStatusT;
        public TextBox K_usTT;
        public TextBox YawRateTT;
        public TextBox L_rT;
        public TextBox betaTT;
        public TextBox K_usT;
        public TextBox YawRateT;
        public TextBox LateralAccTT;
        public TextBox betaT;
        public TextBox CarStatusT;
        public TextBox LateralAccT;
        public TextBox textBox21;
        public TextBox RadiusT;
        public TextBox textBox4;
        public TextBox c_arTT;
        public TextBox textBox20;
        public TextBox textBox3;
        public TextBox c_arT;
        public TextBox m_rT;
        public TextBox TurnSideT;
        public TextBox c_afTT;
        public TextBox AccTT;
        public TextBox c_afT;
        public TextBox AccT;
        public TextBox textBox18;
        public TextBox m_fT;
        public TextBox textBox17;
        public TextBox F_xrT;
        public TextBox alpha_rTT;
        public TextBox alpha_rT;
        public TextBox textBox15;
        public TextBox alpha_fTT;
        public TextBox VelocityTT;
        public TextBox TireAngleTT;
        public TextBox F_xfT;
        public TextBox delta_fTT;
        public TextBox BrakingTiresT;
        public TextBox VelocityZTT;
        public TextBox VelocityXTT;
        public TextBox VelocityZT;
        public TextBox VelocityXT;
        public TextBox VelocityT;
        public TextBox TireAngleT;
        public TextBox alpha_fT;
        public TextBox delta_fT;

        #endregion

        public ESPForm(Texture2D texture, SpriteFont font, Color foreColor, ContentManager contentManager)
            : base("ESPValues", "ESPValues", new Rectangle(0, 12, 300, 750), texture, font, foreColor, null)
        {
            this.contentManager = contentManager;
            this.AddControls();
        }

        void AddControls()
        {
            Texture2D texButton = contentManager.Load<Texture2D>(@"GUI\texButton");
            Texture2D texTextBox = contentManager.Load<Texture2D>(@"GUI\texTextBox");


            Hide = new Button("Hide", @"Hide", new Rectangle(261, 351, 39, 26), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(Hide);

            l_f = new Label("l_f", @"L_f", new Vector2(6, 566), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(l_f);

            L_r = new Label("L_r", @"L_r", new Vector2(6, 540), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(L_r);

            label22 = new Label("label22", @"Yaw Rate", new Vector2(6, 435), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label22);

            label21 = new Label("label21", @"beta", new Vector2(6, 410), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label21);

            label20 = new Label("label20", @"Lateral Acc", new Vector2(6, 385), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label20);

            label12 = new Label("label12", @"Radius", new Vector2(6, 359), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label12);

            label11 = new Label("label11", @"Car Status", new Vector2(6, 40), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label11);

            label10 = new Label("label10", @"Turn Side", new Vector2(6, 65), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label10);

            label9 = new Label("label9", @"ESP Status", new Vector2(6, 13), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label9);

            label8 = new Label("label8", @"K_us", new Vector2(6, 514), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label8);

            label19 = new Label("label19", @"c_ar", new Vector2(6, 488), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label19);

            label24 = new Label("label24", @"m_r", new Vector2(6, 675), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label24);

            label7 = new Label("label7", @"m_r", new Vector2(6, 621), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label7);

            label18 = new Label("label18", @"c_af", new Vector2(6, 462), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label18);

            label23 = new Label("label23", @"Acc", new Vector2(6, 649), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label23);

            label6 = new Label("label6", @"m_f", new Vector2(6, 595), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label6);

            label5 = new Label("label5", @"F_xr", new Vector2(6, 332), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label5);

            label4 = new Label("label4", @"F_xf", new Vector2(6, 306), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label4);

            label3 = new Label("label3", @"alpha_r", new Vector2(6, 280), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label3);

            label2 = new Label("label2", @"alpha_f", new Vector2(6, 254), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label2);

            label13 = new Label("label13", @"Braking Tire", new Vector2(6, 90), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label13);

            label16 = new Label("label16", @"Velocity - Z Axis", new Vector2(6, 168), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label16);

            label15 = new Label("label15", @"Velocity - X Axis", new Vector2(6, 143), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label15);

            label14 = new Label("label14", @"Velocity", new Vector2(6, 115), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label14);

            label17 = new Label("label17", @"Tire Angle", new Vector2(6, 202), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label17);

            label1 = new Label("label1", @"delta_f", new Vector2(6, 228), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label1);

            L_fT = new TextBox("L_fT", @"", 32767, "", new Rectangle(68, 563, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            L_fT.ReadOnly = true;
            this.AddControl(L_fT);

            ESPStatusT = new TextBox("ESPStatusT", @"", 32767, "", new Rectangle(68, 10, 167, 21), texTextBox, font, new Color(0, 0, 0), null);
            ESPStatusT.ReadOnly = true;
            this.AddControl(ESPStatusT);

            K_usTT = new TextBox("K_usTT", @"", 32767, "", new Rectangle(159, 510, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            K_usTT.ReadOnly = true;
            this.AddControl(K_usTT);

            YawRateTT = new TextBox("YawRateTT", @"", 32767, "", new Rectangle(159, 431, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            YawRateTT.ReadOnly = true;
            this.AddControl(YawRateTT);

            L_rT = new TextBox("L_rT", @"", 32767, "", new Rectangle(68, 537, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            L_rT.ReadOnly = true;
            this.AddControl(L_rT);

            betaTT = new TextBox("betaTT", @"", 32767, "", new Rectangle(159, 406, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            betaTT.ReadOnly = true;
            this.AddControl(betaTT);

            K_usT = new TextBox("K_usT", @"", 32767, "", new Rectangle(68, 510, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            K_usT.ReadOnly = true;
            this.AddControl(K_usT);

            YawRateT = new TextBox("YawRateT", @"", 32767, "", new Rectangle(68, 431, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            YawRateT.ReadOnly = true;
            this.AddControl(YawRateT);

            LateralAccTT = new TextBox("LateralAccTT", @"", 32767, "", new Rectangle(159, 381, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            LateralAccTT.ReadOnly = true;
            this.AddControl(LateralAccTT);

            betaT = new TextBox("betaT", @"", 32767, "", new Rectangle(68, 406, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            betaT.ReadOnly = true;
            this.AddControl(betaT);

            CarStatusT = new TextBox("CarStatusT", @"", 32767, "", new Rectangle(68, 37, 167, 21), texTextBox, font, new Color(0, 0, 0), null);
            CarStatusT.ReadOnly = true;
            this.AddControl(CarStatusT);

            LateralAccT = new TextBox("LateralAccT", @"", 32767, "", new Rectangle(68, 381, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            LateralAccT.ReadOnly = true;
            this.AddControl(LateralAccT);

            textBox21 = new TextBox("textBox21", @"", 32767, "", new Rectangle(159, 355, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            textBox21.ReadOnly = true;
            this.AddControl(textBox21);

            RadiusT = new TextBox("RadiusT", @"", 32767, "", new Rectangle(68, 355, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            RadiusT.ReadOnly = true;
            this.AddControl(RadiusT);

            textBox4 = new TextBox("textBox4", @"", 32767, "", new Rectangle(159, 672, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            textBox4.ReadOnly = true;
            this.AddControl(textBox4);

            c_arTT = new TextBox("c_arTT", @"", 32767, "", new Rectangle(159, 485, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            c_arTT.ReadOnly = true;
            this.AddControl(c_arTT);

            textBox20 = new TextBox("textBox20", @"", 32767, "", new Rectangle(159, 618, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            textBox20.ReadOnly = true;
            this.AddControl(textBox20);

            textBox3 = new TextBox("textBox3", @"", 32767, "", new Rectangle(68, 672, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            textBox3.ReadOnly = true;
            this.AddControl(textBox3);

            c_arT = new TextBox("c_arT", @"", 32767, "", new Rectangle(68, 485, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            c_arT.ReadOnly = true;
            this.AddControl(c_arT);

            m_rT = new TextBox("m_rT", @"", 32767, "", new Rectangle(68, 618, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            m_rT.ReadOnly = true;
            this.AddControl(m_rT);

            TurnSideT = new TextBox("TurnSideT", @"", 32767, "", new Rectangle(68, 62, 167, 21), texTextBox, font, new Color(0, 0, 0), null);
            TurnSideT.ReadOnly = true;
            this.AddControl(TurnSideT);

            c_afTT = new TextBox("c_afTT", @"", 32767, "", new Rectangle(159, 459, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            c_afTT.ReadOnly = true;
            this.AddControl(c_afTT);

            AccTT = new TextBox("AccTT", @"", 32767, "", new Rectangle(159, 646, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            AccTT.ReadOnly = true;
            this.AddControl(AccTT);

            c_afT = new TextBox("c_afT", @"", 32767, "", new Rectangle(68, 459, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            c_afT.ReadOnly = true;
            this.AddControl(c_afT);

            AccT = new TextBox("AccT", @"", 32767, "", new Rectangle(68, 646, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            AccT.ReadOnly = true;
            this.AddControl(AccT);

            textBox18 = new TextBox("textBox18", @"", 32767, "", new Rectangle(159, 592, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            textBox18.ReadOnly = true;
            this.AddControl(textBox18);

            m_fT = new TextBox("m_fT", @"", 32767, "", new Rectangle(68, 592, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            m_fT.ReadOnly = true;
            this.AddControl(m_fT);

            textBox17 = new TextBox("textBox17", @"", 32767, "", new Rectangle(159, 328, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            textBox17.ReadOnly = true;
            this.AddControl(textBox17);

            F_xrT = new TextBox("F_xrT", @"", 32767, "", new Rectangle(68, 328, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            F_xrT.ReadOnly = true;
            this.AddControl(F_xrT);

            alpha_rTT = new TextBox("alpha_rTT", @"", 32767, "", new Rectangle(159, 276, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            alpha_rTT.ReadOnly = true;
            this.AddControl(alpha_rTT);

            alpha_rT = new TextBox("alpha_rT", @"", 32767, "", new Rectangle(68, 276, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            alpha_rT.ReadOnly = true;
            this.AddControl(alpha_rT);

            textBox15 = new TextBox("textBox15", @"", 32767, "", new Rectangle(159, 302, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            textBox15.ReadOnly = true;
            this.AddControl(textBox15);

            alpha_fTT = new TextBox("alpha_fTT", @"", 32767, "", new Rectangle(159, 250, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            alpha_fTT.ReadOnly = true;
            this.AddControl(alpha_fTT);

            VelocityTT = new TextBox("VelocityTT", @"", 32767, "", new Rectangle(159, 111, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            VelocityTT.ReadOnly = true;
            this.AddControl(VelocityTT);

            TireAngleTT = new TextBox("TireAngleTT", @"", 32767, "", new Rectangle(159, 198, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            TireAngleTT.ReadOnly = true;
            this.AddControl(TireAngleTT);

            F_xfT = new TextBox("F_xfT", @"", 32767, "", new Rectangle(68, 302, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            F_xfT.ReadOnly = true;
            this.AddControl(F_xfT);

            delta_fTT = new TextBox("delta_fTT", @"", 32767, "", new Rectangle(159, 224, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            delta_fTT.ReadOnly = true;
            this.AddControl(delta_fTT);

            BrakingTiresT = new TextBox("BrakingTiresT", @"", 32767, "", new Rectangle(68, 86, 167, 21), texTextBox, font, new Color(0, 0, 0), null);
            BrakingTiresT.ReadOnly = true;
            this.AddControl(BrakingTiresT);

            VelocityZTT = new TextBox("VelocityZTT", @"", 32767, "", new Rectangle(159, 168, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            VelocityZTT.ReadOnly = true;
            this.AddControl(VelocityZTT);

            VelocityXTT = new TextBox("VelocityXTT", @"", 32767, "", new Rectangle(159, 140, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            VelocityXTT.ReadOnly = true;
            this.AddControl(VelocityXTT);

            VelocityZT = new TextBox("VelocityZT", @"", 32767, "", new Rectangle(83, 168, 70, 21), texTextBox, font, new Color(0, 0, 0), null);
            VelocityZT.ReadOnly = true;
            this.AddControl(VelocityZT);

            VelocityXT = new TextBox("VelocityXT", @"", 32767, "", new Rectangle(83, 140, 70, 21), texTextBox, font, new Color(0, 0, 0), null);
            VelocityXT.ReadOnly = true;
            this.AddControl(VelocityXT);

            VelocityT = new TextBox("VelocityT", @"", 32767, "", new Rectangle(68, 111, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            VelocityT.ReadOnly = true;
            this.AddControl(VelocityT);

            TireAngleT = new TextBox("TireAngleT", @"", 32767, "", new Rectangle(68, 198, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            TireAngleT.ReadOnly = true;
            this.AddControl(TireAngleT);

            alpha_fT = new TextBox("alpha_fT", @"", 32767, "", new Rectangle(68, 250, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            alpha_fT.ReadOnly = true;
            this.AddControl(alpha_fT);

            delta_fT = new TextBox("delta_fT", @"", 32767, "", new Rectangle(68, 224, 85, 21), texTextBox, font, new Color(0, 0, 0), null);
            delta_fT.ReadOnly = true;
            this.AddControl(delta_fT);


        }
    }
}