/*
 *Generated by FuchsGUICodeGenerator
 *Ghoshehsoft@live.com
 *www.ghoshehsoft.wordpress.com
 *Time of generation: 2/9/2011 3:12:07 AM
*/

using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Content;

using FuchsGUI;

namespace GUI
{
    public sealed class GPSForm : Form
    {
        ContentManager contentManager;

        #region Fields

        public Button editeGraphWeight;
        public Button Hide;
        public Button defineDestination;
        public Label label4;
        public Label label2;
        public Label label5;
        public Label label3;
        public TextBox textBox2;
        public Label label1;
        public TextBox textBox5;
        public TextBox textBox4;
        public TextBox textBox3;
        public TextBox textBox1;

        #endregion

        public GPSForm(Texture2D texture, SpriteFont font, Color foreColor, ContentManager contentManager)
            : base("groupBox1", "GPS Form", new Rectangle(12, 12, 300, 750), texture, font, foreColor, null)
        {
            this.contentManager = contentManager;
            this.AddControls();
        }

        void AddControls()
        {
            Texture2D texButton = contentManager.Load<Texture2D>(@"GUI\texButton");
            Texture2D texTextBox = contentManager.Load<Texture2D>(@"GUI\texTextBox");


            Hide = new Button("Hide", @"Hide", new Rectangle(259, 359, 41, 26), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(Hide);

            editeGraphWeight = new Button("editeGraphWeight", @"Edit Graph Weights", new Rectangle(26, 487, 167, 36), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(editeGraphWeight);

            defineDestination = new Button("Define Destination", @"defineDestination", new Rectangle(50, 100, 100, 26), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(defineDestination);

            label4 = new Label("label4", @"Source Point", new Vector2(26, 206), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label4);

            label2 = new Label("label2", @"Destination Point", new Vector2(26, 265), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label2);

            label5 = new Label("label5", @"Link Weight", new Vector2(26, 446), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label5);

            label3 = new Label("label3", @"Current GPS Point Position", new Vector2(26, 372), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label3);

            textBox2 = new TextBox("textBox2", @"", 32767, "", new Rectangle(26, 462, 167, 21), texTextBox, font, new Color(0, 0, 0), null);
            this.AddControl(textBox2);

            label1 = new Label("label1", @"Current Car Position", new Vector2(26, 315), font, new Color(0, 0, 0), 0, 0, null);
            this.AddControl(label1);

            textBox5 = new TextBox("textBox5", @"", 32767, "", new Rectangle(26, 388, 167, 21), texTextBox, font, new Color(0, 0, 0), null);
            textBox5.ReadOnly = true;
            this.AddControl(textBox5);

            textBox4 = new TextBox("textBox4", @"", 32767, "", new Rectangle(29, 281, 167, 21), texTextBox, font, new Color(0, 0, 0), null);
            textBox4.ReadOnly = true;
            this.AddControl(textBox4);

            textBox3 = new TextBox("textBox3", @"", 32767, "", new Rectangle(29, 233, 167, 21), texTextBox, font, new Color(0, 0, 0), null);
            textBox3.ReadOnly = true;
            this.AddControl(textBox3);

            textBox1 = new TextBox("textBox1", @"", 32767, "", new Rectangle(26, 331, 167, 21), texTextBox, font, new Color(0, 0, 0), null);
            textBox1.ReadOnly = true;
            this.AddControl(textBox1);


        }
    }
}