/*
 *Generated by FuchsGUICodeGenerator
 *Ghoshehsoft@live.com
 *www.ghoshehsoft.wordpress.com
 *Time of generation: 2/9/2011 8:51:26 AM
*/

using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Content;

using FuchsGUI;

namespace GUI
{
    public sealed class InitializationForm : Form
    {
        ContentManager contentManager;

        #region Fields

        public Button Submit;
        public Label label7;
        public TextBox textBox1;
        public Label label8;
        public Label label66;
        public TextBox VehicleHeigh;
        public Label label67;
        public Label label5;
        public TextBox GravityConst;
        public Label label6;
        public TextBox VehicleWidth;
        public Label label13;
        public Label label14;
        public TextBox RollingCoeff;
        public Label label12;
        public Label label9;
        public Label label10;
        public TextBox DragCoeff;
        public Label label3;
        public Label label4;
        public TextBox WheelRadius;
        public Label label2;
        public Label label1;
        public TextBox VehicelWieght;
        public Form gBCar;
        public Label label31;
        public Label label30;
        public Label label52;
        public TextBox textBox15;
        public TextBox textBox27;
        public Form gBGPS;
        public TextBox textBox14;
        public Label label28;
        public TextBox textBox6;
        public TextBox textBox5;
        public TextBox textBox4;
        public TextBox textBox3;
        public TextBox textBox2;
        public Label label71;
        public Label label69;
        public Label label27;
        public Label label73;
        public Label label72;
        public Label label70;
        public Label label68;
        public Form gBESP;

        #endregion

        public InitializationForm(Texture2D texture, SpriteFont font, Color foreColor, ContentManager contentManager)
            : base("MainMenu", "Main Menu", new Rectangle(0, 0, 1366, 768), texture, font, foreColor, null)
        {
            this.contentManager = contentManager;
            this.AddControls();
        }

        void AddControls()
        {
            Texture2D texButton = contentManager.Load<Texture2D>(@"GUI\texButton");
            Texture2D texTextBox = contentManager.Load<Texture2D>(@"GUI\texTextBox");
            Texture2D texForm = contentManager.Load<Texture2D>(@"GUI\texForm");


            Submit = new Button("Submit", @"Submit", new Rectangle(583, 240, 135, 40), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(Submit);

            gBCar = new Form("gBCar", @"Car's Variables", new Rectangle(325, 34, 208, 430), texForm, font, new Color(0, 0, 0), null);
            label7 = new Label("label7", @"M", new Vector2(177, 173), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label7);

            textBox1 = new TextBox("textBox1", @"0.7", 8, "0123456789-+.", new Rectangle(96, 325, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBCar.AddControl(textBox1);

            label8 = new Label("label8", @"Vehicle Height", new Vector2(7, 173), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label8);

            label66 = new Label("label66", @"", new Vector2(170, 328), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label66);

            VehicleHeigh = new TextBox("VehicleHeigh", @"1.28", 8, "0123456789-+.", new Rectangle(90, 170, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBCar.AddControl(VehicleHeigh);

            label67 = new Label("label67", @"Differential Ratio", new Vector2(7, 328), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label67);

            label5 = new Label("label5", @"M", new Vector2(177, 144), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label5);

            GravityConst = new TextBox("GravityConst", @"9.8", 8, "0123456789-+.", new Rectangle(95, 301, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBCar.AddControl(GravityConst);

            label6 = new Label("label6", @"Vehicle Width", new Vector2(7, 147), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label6);

            VehicleWidth = new TextBox("VehicleWidth", @"1.87", 8, "0123456789-+.", new Rectangle(90, 144, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBCar.AddControl(VehicleWidth);

            label13 = new Label("label13", @"M/S^2", new Vector2(169, 304), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label13);

            label14 = new Label("label14", @"Gravity Constant", new Vector2(6, 304), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label14);

            RollingCoeff = new TextBox("RollingCoeff", @"0.015", 8, "0123456789-+.", new Rectangle(95, 278, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBCar.AddControl(RollingCoeff);

            label12 = new Label("label12", @"Rolling Coefficient", new Vector2(6, 281), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label12);

            label9 = new Label("label9", @"", new Vector2(177, 257), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label9);

            label10 = new Label("label10", @"Drag Coefficient", new Vector2(6, 257), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label10);

            DragCoeff = new TextBox("DragCoeff", @"0.31", 8, "0123456789-+.", new Rectangle(95, 254, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBCar.AddControl(DragCoeff);

            label3 = new Label("label3", @"M", new Vector2(177, 94), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label3);

            label4 = new Label("label4", @"Wheel Radius", new Vector2(6, 94), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label4);

            WheelRadius = new TextBox("WheelRadius", @"0.31", 8, "0123456789-+.", new Rectangle(95, 91, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBCar.AddControl(WheelRadius);

            label2 = new Label("label2", @"KG", new Vector2(177, 53), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label2);

            label1 = new Label("label1", @"Vehicle Mass", new Vector2(6, 53), font, new Color(0, 0, 0), 0, 0, null);
            gBCar.AddControl(label1);

            VehicelWieght = new TextBox("VehicelWieght", @"1850", 8, "0123456789", new Rectangle(95, 50, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBCar.AddControl(VehicelWieght);

            this.AddControl(gBCar);

            gBGPS = new Form("gBGPS", @"GPS's Variables", new Rectangle(798, 291, 208, 173), texForm, font, new Color(0, 0, 0), null);
            label31 = new Label("label31", @"Z", new Vector2(27, 102), font, new Color(0, 0, 0), 0, 0, null);
            gBGPS.AddControl(label31);

            label30 = new Label("label30", @"X", new Vector2(27, 79), font, new Color(0, 0, 0), 0, 0, null);
            gBGPS.AddControl(label30);

            label52 = new Label("label52", @"Destination Point", new Vector2(6, 53), font, new Color(0, 0, 0), 0, 0, null);
            gBGPS.AddControl(label52);

            textBox15 = new TextBox("textBox15", @"", 8, "", new Rectangle(55, 99, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBGPS.AddControl(textBox15);

            textBox27 = new TextBox("textBox27", @"", 8, "", new Rectangle(55, 76, 76, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBGPS.AddControl(textBox27);

            this.AddControl(gBGPS);

            gBESP = new Form("gBESP", @"ESP's Variables", new Rectangle(798, 34, 208, 246), texForm, font, new Color(0, 0, 0), null);
            textBox14 = new TextBox("textBox14", @"1500", 8, "0123456789", new Rectangle(97, 53, 105, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBESP.AddControl(textBox14);

            label28 = new Label("label28", @"Mass", new Vector2(9, 56), font, new Color(0, 0, 0), 0, 0, null);
            gBESP.AddControl(label28);

            textBox6 = new TextBox("textBox6", @"1.0", 8, "0123456789-+.", new Rectangle(99, 215, 105, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBESP.AddControl(textBox6);

            textBox5 = new TextBox("textBox5", @"1.2", 8, "0123456789-+.", new Rectangle(99, 190, 105, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBESP.AddControl(textBox5);

            textBox4 = new TextBox("textBox4", @"144.93", 8, "0123456789-+.", new Rectangle(100, 167, 105, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBESP.AddControl(textBox4);

            textBox3 = new TextBox("textBox3", @"117.44", 8, "0123456789-+.", new Rectangle(100, 144, 105, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBESP.AddControl(textBox3);

            textBox2 = new TextBox("textBox2", @"0.508", 8, "0123456789-+.", new Rectangle(12, 96, 189, 21), texTextBox, font, new Color(0, 0, 0), null);
            gBESP.AddControl(textBox2);

            label71 = new Label("label71", @"", new Vector2(175, 147), font, new Color(0, 0, 0), 0, 0, null);
            gBESP.AddControl(label71);

            label69 = new Label("label69", @"", new Vector2(172, 76), font, new Color(0, 0, 0), 0, 0, null);
            gBESP.AddControl(label69);

            label27 = new Label("label27", @"L_r", new Vector2(11, 218), font, new Color(0, 0, 0), 0, 0, null);
            gBESP.AddControl(label27);

            label73 = new Label("label73", @"L_f", new Vector2(11, 193), font, new Color(0, 0, 0), 0, 0, null);
            gBESP.AddControl(label73);

            label72 = new Label("label72", @"c_ar", new Vector2(12, 170), font, new Color(0, 0, 0), 0, 0, null);
            gBESP.AddControl(label72);

            label70 = new Label("label70", @"c_af", new Vector2(12, 147), font, new Color(0, 0, 0), 0, 0, null);
            gBESP.AddControl(label70);

            label68 = new Label("label68", @"heightOfCenterOfGravity", new Vector2(9, 76), font, new Color(0, 0, 0), 0, 0, null);
            gBESP.AddControl(label68);

            this.AddControl(gBESP);


        }
    }
}