/*
 *Generated by FuchsGUICodeGenerator
 *Ghoshehsoft@live.com
 *www.ghoshehsoft.wordpress.com
 *Time of generation: 2/9/2011 3:31:30 AM
*/

using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Content;

using FuchsGUI;

namespace GUI
{
    public sealed class MainForm : Form
    {
        ContentManager contentManager;

        #region Fields

        public Button GPS;
        public Button Brake_Data_Form;
        public Button Exit;
        public Button ESP;
        public Button CamerasControl;
        public Button ABS;

        #endregion

        public MainForm(Texture2D texture, SpriteFont font, Color foreColor, ContentManager contentManager)
            : base("groupBox1", "Main Control", new Rectangle(0, 12, 123, 299), texture, font, foreColor, null)
        {
            this.contentManager = contentManager;
            this.AddControls();
        }

        void AddControls()
        {
            Texture2D texButton = contentManager.Load<Texture2D>(@"GUI\texButton");


            GPS = new Button("GPS", @"GPS", new Rectangle(0, 189, 122, 32), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(GPS);

            Brake_Data_Form = new Button("Brake_Data_Form", @"Brake Data Form", new Rectangle(0, 151, 122, 32), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(Brake_Data_Form);

            Exit = new Button("Exit", @"Exit", new Rectangle(0, 227, 122, 32), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(Exit);

            ESP = new Button("ESB", @"ESB", new Rectangle(0, 113, 122, 32), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(ESP);

            CamerasControl = new Button("CamerasControl", @"Cameras Control", new Rectangle(0, 37, 122, 32), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(CamerasControl);

            ABS = new Button("ABS", @"ABS", new Rectangle(0, 75, 122, 32), texButton, font, new Color(0, 0, 0), null);
            this.AddControl(ABS);


        }
    }
}